version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - API_PORT=80
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    volumes:
      - api_data:/app/api/data

volumes:
  api_data: 