[phases.setup]
nixPkgs = ["nodejs", "npm", "sqlite"]

[phases.install]
workingDirectory = "./"
cmds = ["cd api && npm install"]

[phases.build]
workingDirectory = "./"
cmds = ["cd api && npm run build"]

[start]
workingDirectory = "./"
cmd = "cd api && NODE_ENV=production PORT=80 node simple-server.js"

[variables]
NODE_ENV = "production"
PORT = "80"
API_PORT = "80"
HOSTNAME = "0.0.0.0" 