version: '3'

services:
  api:
    build:
      context: .
      dockerfile: .coolify/Dockerfile
    ports:
      - "8888:8888"
    environment:
      - NODE_ENV=production
      - PORT=8888
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    volumes:
      - api_data:/app/api/data

volumes:
  api_data: 